const pool = require('./config/database');
const bcrypt = require('bcryptjs');
const fs = require('fs');
const path = require('path');

async function seed() {
  const client = await pool.connect();

  try {
    console.log('Starting database seed...');

    // Read and execute schema
    const schemaPath = path.join(__dirname, 'config', 'schema.sql');
    const schema = fs.readFileSync(schemaPath, 'utf8');
    await client.query(schema);
    console.log('Schema created successfully');

    // Clear existing data
    await client.query('TRUNCATE users, ad_copies, email_campaigns, social_posts, product_descriptions, blog_posts, landing_pages, taglines, seo_content, press_releases, video_scripts RESTART IDENTITY CASCADE');
    console.log('Cleared existing data');

    // Create demo user
    const hashedPassword = await bcrypt.hash('demo123', 10);
    const userResult = await client.query(
      'INSERT INTO users (email, password, name, company) VALUES ($1, $2, $3, $4) RETURNING id',
      ['demo@aimarketing.com', hashedPassword, 'Demo User', 'AI Marketing Co']
    );
    const userId = userResult.rows[0].id;
    console.log('Demo user created');

    // Seed Ad Copies (15 items)
    const adCopies = [
      { title: 'Summer Sale Facebook Ad', platform: 'Facebook', target_audience: 'Young Adults 18-35', tone: 'Exciting', content: 'Beat the heat with our sizzling summer deals! Up to 50% off on all products. Limited time only - shop now and save big! Your summer wardrobe awaits.', cta: 'Shop Now', status: 'published' },
      { title: 'Google Search Ad - Software', platform: 'Google Ads', target_audience: 'Business Owners', tone: 'Professional', content: 'Streamline Your Business Operations | Award-Winning Software | Free Trial Available | Join 10,000+ Companies', cta: 'Start Free Trial', status: 'published' },
      { title: 'Instagram Story Ad', platform: 'Instagram', target_audience: 'Fashion Enthusiasts', tone: 'Trendy', content: 'New Collection Just Dropped! Swipe up to discover the latest trends that will make heads turn. Be the first to rock these exclusive pieces.', cta: 'Swipe Up', status: 'published' },
      { title: 'LinkedIn B2B Campaign', platform: 'LinkedIn', target_audience: 'C-Level Executives', tone: 'Authoritative', content: 'Transform your enterprise with AI-powered analytics. Trusted by Fortune 500 companies. See how leaders are making data-driven decisions.', cta: 'Request Demo', status: 'draft' },
      { title: 'TikTok Product Launch', platform: 'TikTok', target_audience: 'Gen Z', tone: 'Fun', content: 'POV: You just discovered the product that changes everything. No cap, this is actually amazing. Link in bio!', cta: 'Get Yours', status: 'published' },
      { title: 'YouTube Pre-Roll Ad', platform: 'YouTube', target_audience: 'Tech Enthusiasts', tone: 'Informative', content: 'In just 15 seconds, discover why millions switched to our platform. Faster, smarter, better - see the difference yourself.', cta: 'Learn More', status: 'published' },
      { title: 'Twitter Engagement Ad', platform: 'Twitter', target_audience: 'News Followers', tone: 'Conversational', content: 'Still using outdated tools? Join the conversation about modern solutions. See what 50K+ users are saying about us.', cta: 'Join Now', status: 'draft' },
      { title: 'Pinterest Shopping Ad', platform: 'Pinterest', target_audience: 'Home Decorators', tone: 'Inspirational', content: 'Create the home of your dreams. Our curated collection brings designer aesthetics at accessible prices. Pin your favorites!', cta: 'Explore Collection', status: 'published' },
      { title: 'Retargeting Display Ad', platform: 'Display Network', target_audience: 'Website Visitors', tone: 'Urgent', content: 'You left something behind! Complete your purchase today and get 15% off. Your cart is waiting - offer expires soon.', cta: 'Complete Purchase', status: 'published' },
      { title: 'App Install Campaign', platform: 'Mobile Ads', target_audience: 'Smartphone Users', tone: 'Exciting', content: 'Join 5 million users who have transformed their daily routine. Download now and get premium features free for 30 days!', cta: 'Download Free', status: 'published' },
      { title: 'Holiday Special Ad', platform: 'Facebook', target_audience: 'Gift Shoppers', tone: 'Festive', content: 'Make this holiday season unforgettable! Exclusive gifts, unbeatable prices, and free shipping on orders over $50.', cta: 'Shop Gifts', status: 'draft' },
      { title: 'Webinar Promotion Ad', platform: 'LinkedIn', target_audience: 'Marketing Professionals', tone: 'Educational', content: 'Free Masterclass: Learn the secrets of high-converting campaigns from industry experts. Limited seats available.', cta: 'Reserve Seat', status: 'published' },
      { title: 'Local Business Ad', platform: 'Google Ads', target_audience: 'Local Customers', tone: 'Friendly', content: 'Your neighborhood experts since 2010. Quality service, fair prices, and a smile. Visit us today!', cta: 'Get Directions', status: 'published' },
      { title: 'Flash Sale Ad', platform: 'Instagram', target_audience: 'Bargain Hunters', tone: 'Urgent', content: '24 HOURS ONLY! Everything must go. Up to 70% off selected items. Set your alarms - this won\'t last!', cta: 'Shop Sale', status: 'published' },
      { title: 'Subscription Box Ad', platform: 'Facebook', target_audience: 'Lifestyle Enthusiasts', tone: 'Curious', content: 'What\'s in the box? Curated surprises delivered monthly. Join thousands who look forward to their doorstep deliveries.', cta: 'Subscribe Now', status: 'draft' }
    ];

    for (const ad of adCopies) {
      await client.query(
        'INSERT INTO ad_copies (user_id, title, platform, target_audience, tone, content, cta, status) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)',
        [userId, ad.title, ad.platform, ad.target_audience, ad.tone, ad.content, ad.cta, ad.status]
      );
    }
    console.log('Ad copies seeded: 15 items');

    // Seed Email Campaigns (15 items)
    const emailCampaigns = [
      { subject: 'Welcome to AI Marketing - Let\'s Get Started!', campaign_type: 'Welcome', target_segment: 'New Subscribers', body: 'Hi there!\n\nWelcome to AI Marketing! We\'re thrilled to have you on board.\n\nHere\'s what you can expect:\n- Weekly tips and insights\n- Exclusive member discounts\n- Early access to new features\n\nLet\'s create something amazing together!\n\nBest,\nThe AI Marketing Team', preview_text: 'Your journey to better marketing starts now', status: 'sent', open_rate: 45.5, click_rate: 12.3 },
      { subject: 'Your Weekly Marketing Digest', campaign_type: 'Newsletter', target_segment: 'Active Users', body: 'This Week in Marketing:\n\n1. AI Trends Reshaping Advertising\n2. 5 Tips for Better Email Open Rates\n3. Case Study: 300% ROI Campaign\n\nRead more on our blog...', preview_text: 'Top stories and insights for marketers', status: 'sent', open_rate: 38.2, click_rate: 8.7 },
      { subject: 'Don\'t Miss Out - 48 Hours Left!', campaign_type: 'Promotional', target_segment: 'All Subscribers', body: 'Time is running out!\n\nOur biggest sale of the year ends in 48 hours. Get 40% off all annual plans with code SAVE40.\n\nUpgrade now and unlock:\n- Unlimited AI generations\n- Priority support\n- Advanced analytics\n\nDon\'t wait - this offer won\'t come back!', preview_text: 'Last chance for 40% off annual plans', status: 'sent', open_rate: 52.1, click_rate: 18.4 },
      { subject: 'We Miss You! Here\'s 20% Off', campaign_type: 'Re-engagement', target_segment: 'Inactive Users', body: 'It\'s been a while!\n\nWe noticed you haven\'t logged in recently, and we wanted to check in. To welcome you back, here\'s an exclusive 20% discount on your next purchase.\n\nUse code: COMEBACK20\n\nWe\'ve added some exciting new features you might love...', preview_text: 'Come back and save 20% today', status: 'sent', open_rate: 28.9, click_rate: 6.2 },
      { subject: 'Your Monthly Performance Report', campaign_type: 'Transactional', target_segment: 'Premium Users', body: 'Your January Report is Ready!\n\nKey Metrics:\n- Content Generated: 247 pieces\n- Time Saved: 42 hours\n- Engagement Score: 8.7/10\n\nTop Performing Content:\n1. Summer Sale Ad (15.2% CTR)\n2. Product Launch Email (48% Open Rate)\n\nView full report in your dashboard.', preview_text: 'See how your content performed this month', status: 'sent', open_rate: 61.3, click_rate: 34.5 },
      { subject: 'New Feature Alert: AI Video Scripts!', campaign_type: 'Product Update', target_segment: 'All Users', body: 'Exciting News!\n\nWe\'ve just launched AI Video Scripts - create professional video content in minutes!\n\nWhat\'s New:\n- YouTube script generator\n- TikTok content ideas\n- Commercial storyboards\n\nTry it now in your dashboard!', preview_text: 'Create video content with AI', status: 'sent', open_rate: 44.7, click_rate: 22.1 },
      { subject: 'Invitation: Exclusive Webinar for Members', campaign_type: 'Event', target_segment: 'Premium Users', body: 'You\'re Invited!\n\nJoin us for an exclusive masterclass:\n"10X Your Marketing with AI"\n\nDate: February 15, 2024\nTime: 2:00 PM EST\nHost: Sarah Johnson, CMO\n\nSeats are limited - reserve yours now!', preview_text: 'Join our exclusive marketing masterclass', status: 'scheduled', open_rate: null, click_rate: null },
      { subject: 'Quick Survey: Help Us Improve', campaign_type: 'Survey', target_segment: 'Active Users', body: 'We Value Your Opinion!\n\nTake our 2-minute survey and help shape the future of AI Marketing.\n\nAs a thank you, you\'ll receive:\n- 100 bonus credits\n- Entry to win a free year subscription\n\nYour feedback matters!', preview_text: 'Share your thoughts, earn rewards', status: 'sent', open_rate: 33.8, click_rate: 14.2 },
      { subject: 'Happy Birthday! A Gift Just for You', campaign_type: 'Birthday', target_segment: 'Birthday Celebrants', body: 'Happy Birthday!\n\nTo celebrate your special day, we\'re giving you:\n\n🎁 50% OFF any plan for the next 24 hours\n\nUse code: BDAY50\n\nWishing you an amazing year ahead!\n\nCheers,\nYour AI Marketing Family', preview_text: 'Celebrate with 50% off!', status: 'automated', open_rate: 58.9, click_rate: 25.7 },
      { subject: 'Case Study: How Brand X Grew 500%', campaign_type: 'Educational', target_segment: 'Trial Users', body: 'Real Results, Real Business\n\nDiscover how Brand X used AI Marketing to:\n- Increase conversions by 500%\n- Reduce content costs by 80%\n- Save 100+ hours monthly\n\nRead the full case study and learn their exact strategies...', preview_text: 'Learn how Brand X achieved 500% growth', status: 'sent', open_rate: 41.2, click_rate: 15.8 },
      { subject: 'Your Trial Ends Tomorrow', campaign_type: 'Trial Expiry', target_segment: 'Trial Users', body: 'Your Free Trial Ends Tomorrow!\n\nDon\'t lose access to:\n- Unlimited AI generations\n- All premium templates\n- Advanced analytics\n\nUpgrade now and get 30% off your first month!\n\nUse code: UPGRADE30', preview_text: 'Keep your AI marketing tools', status: 'automated', open_rate: 55.4, click_rate: 28.9 },
      { subject: 'Thank You for Your Purchase!', campaign_type: 'Order Confirmation', target_segment: 'Customers', body: 'Order Confirmed!\n\nThank you for your purchase. Here are your order details:\n\nPlan: Professional Annual\nAmount: $299/year\nStart Date: Today\n\nYou now have access to all premium features. Get started in your dashboard!', preview_text: 'Your order has been confirmed', status: 'automated', open_rate: 72.1, click_rate: 45.3 },
      { subject: 'Tips to Get the Most from AI Marketing', campaign_type: 'Onboarding', target_segment: 'New Users', body: 'Pro Tips for New Users\n\nMaximize your AI Marketing experience:\n\n1. Complete your brand profile\n2. Try all content types\n3. Use the tone customizer\n4. Save your favorites\n5. Schedule weekly reports\n\nNeed help? Our team is here 24/7!', preview_text: 'Get more from your subscription', status: 'automated', open_rate: 49.8, click_rate: 21.4 },
      { subject: 'Your Payment Failed - Action Required', campaign_type: 'Payment Failed', target_segment: 'Payment Issues', body: 'Payment Update Needed\n\nWe couldn\'t process your recent payment. To avoid service interruption, please update your payment method.\n\nUpdate Payment →\n\nIf you have questions, our support team is ready to help.', preview_text: 'Please update your payment method', status: 'automated', open_rate: 68.5, click_rate: 52.1 },
      { subject: 'Spring Marketing Trends You Need to Know', campaign_type: 'Newsletter', target_segment: 'All Subscribers', body: 'Spring 2024 Marketing Trends\n\n🌸 What\'s Hot This Season:\n\n1. Short-form video dominance\n2. AI-personalized experiences\n3. Sustainability messaging\n4. Interactive content\n5. Voice search optimization\n\nRead our full trend report...', preview_text: 'Stay ahead with spring trends', status: 'draft', open_rate: null, click_rate: null }
    ];

    for (const email of emailCampaigns) {
      await client.query(
        'INSERT INTO email_campaigns (user_id, subject, campaign_type, target_segment, body, preview_text, status, open_rate, click_rate) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)',
        [userId, email.subject, email.campaign_type, email.target_segment, email.body, email.preview_text, email.status, email.open_rate, email.click_rate]
      );
    }
    console.log('Email campaigns seeded: 15 items');

    // Seed Social Posts (15 items)
    const socialPosts = [
      { platform: 'Instagram', content: 'Behind the scenes of our latest product shoot! Can you guess what\'s coming? 👀 Stay tuned for the big reveal this Friday!', hashtags: '#BehindTheScenes #ComingSoon #NewProduct #Excited', scheduled_date: '2024-02-15 10:00:00', engagement_score: 87, status: 'published' },
      { platform: 'Twitter', content: 'Just hit 100K users! 🎉 Thank you to everyone who believed in us from day one. This is just the beginning. #Milestone #Grateful #StartupLife', hashtags: '#Milestone #Grateful #StartupLife', scheduled_date: '2024-02-10 14:30:00', engagement_score: 92, status: 'published' },
      { platform: 'LinkedIn', content: 'Proud to announce we\'ve been named a Top 50 AI Company by TechCrunch! This recognition belongs to our incredible team and customers who push us to innovate every day.', hashtags: '#AI #Innovation #TechCrunch #Award', scheduled_date: '2024-02-12 09:00:00', engagement_score: 78, status: 'published' },
      { platform: 'Facebook', content: 'Weekend vibes! ☀️ Our team is taking a well-deserved break, but we\'re still here for you. Drop your questions below and we\'ll answer them Monday morning!', hashtags: '#WeekendVibes #Community #AskUsAnything', scheduled_date: '2024-02-17 16:00:00', engagement_score: 65, status: 'scheduled' },
      { platform: 'TikTok', content: 'POV: When your AI-generated ad copy gets a 15% CTR 🤯 #MarketingWins #AI #DigitalMarketing #POV', hashtags: '#MarketingWins #AI #DigitalMarketing #POV #Viral', scheduled_date: '2024-02-14 18:00:00', engagement_score: 95, status: 'published' },
      { platform: 'Instagram', content: 'Monday motivation: "The best marketing doesn\'t feel like marketing." - Tom Fishburne\n\nWhat quote keeps you inspired? Share below! 💭', hashtags: '#MondayMotivation #MarketingQuotes #Inspiration', scheduled_date: '2024-02-19 08:00:00', engagement_score: 71, status: 'scheduled' },
      { platform: 'Twitter', content: 'Hot take: AI won\'t replace marketers. Marketers who use AI will replace marketers who don\'t. 🔥\n\nAgree or disagree?', hashtags: '#AI #MarketingTrends #HotTake', scheduled_date: '2024-02-13 12:00:00', engagement_score: 88, status: 'published' },
      { platform: 'LinkedIn', content: '5 AI tools every marketer should know in 2024:\n\n1. ChatGPT for ideation\n2. Midjourney for visuals\n3. AI Marketing for copy\n4. Jasper for long-form\n5. Copy.ai for variations\n\nWhat would you add to this list?', hashtags: '#AITools #Marketing2024 #MarTech', scheduled_date: '2024-02-16 11:00:00', engagement_score: 82, status: 'published' },
      { platform: 'Facebook', content: '🎁 GIVEAWAY TIME! 🎁\n\nWe\'re giving away 3 months of our Pro plan to ONE lucky winner!\n\nTo enter:\n1. Like this post\n2. Follow our page\n3. Tag 2 friends who need better marketing\n\nWinner announced Feb 28!', hashtags: '#Giveaway #FreeStuff #MarketingTools', scheduled_date: '2024-02-20 15:00:00', engagement_score: 94, status: 'scheduled' },
      { platform: 'TikTok', content: 'The face I make when a client says "make it pop" without any other feedback 😐 #MarketingProblems #ClientLife #Relatable', hashtags: '#MarketingProblems #ClientLife #Relatable #Funny', scheduled_date: '2024-02-11 19:00:00', engagement_score: 97, status: 'published' },
      { platform: 'Instagram', content: 'New blog alert! 📝 "10 Copywriting Mistakes That Are Killing Your Conversions"\n\nLink in bio to read the full article and level up your copy game!', hashtags: '#Copywriting #ConversionOptimization #BlogPost #Marketing', scheduled_date: '2024-02-18 13:00:00', engagement_score: 68, status: 'scheduled' },
      { platform: 'Twitter', content: 'Quick tip: The best time to post on Instagram in 2024?\n\n📱 Weekdays: 11am-1pm\n📱 Saturdays: 9-11am\n📱 Sundays: Skip it\n\nSave this for later! 🔖', hashtags: '#SocialMediaTips #InstagramMarketing #QuickTip', scheduled_date: '2024-02-09 10:30:00', engagement_score: 79, status: 'published' },
      { platform: 'LinkedIn', content: 'Just wrapped up our Q1 planning session. Key focus areas:\n\n→ Product innovation\n→ Customer success\n→ Team growth\n→ Community building\n\nExcited for what\'s ahead! What are your Q1 priorities?', hashtags: '#Q1Planning #BusinessStrategy #Leadership', scheduled_date: '2024-02-08 08:30:00', engagement_score: 74, status: 'published' },
      { platform: 'Facebook', content: 'Customer spotlight! 🌟\n\nMeet Sarah from @TechStartupXYZ who increased her email open rates by 47% using our AI copy tools.\n\n"I never thought writing could be this easy!" - Sarah\n\nRead her full story on our blog.', hashtags: '#CustomerSpotlight #SuccessStory #Testimonial', scheduled_date: '2024-02-21 14:00:00', engagement_score: 72, status: 'draft' },
      { platform: 'TikTok', content: 'Rating marketing buzzwords from 1-10:\n\nSynergy: 3/10 🙄\nROI: 9/10 💰\nDisrupt: 4/10 😬\nScalable: 7/10 ✅\nViral: 2/10 🦠\n\nWhat did I miss?', hashtags: '#MarketingBuzzwords #Rating #Funny #Marketing', scheduled_date: '2024-02-22 17:00:00', engagement_score: 91, status: 'draft' }
    ];

    for (const post of socialPosts) {
      await client.query(
        'INSERT INTO social_posts (user_id, platform, content, hashtags, scheduled_date, engagement_score, status) VALUES ($1, $2, $3, $4, $5, $6, $7)',
        [userId, post.platform, post.content, post.hashtags, post.scheduled_date, post.engagement_score, post.status]
      );
    }
    console.log('Social posts seeded: 15 items');

    // Seed Product Descriptions (15 items)
    const productDescriptions = [
      { product_name: 'ProMax Wireless Earbuds', category: 'Electronics', short_description: 'Premium wireless earbuds with active noise cancellation and 40-hour battery life.', long_description: 'Experience audio perfection with ProMax Wireless Earbuds. Featuring advanced active noise cancellation technology, these earbuds create your personal sound sanctuary anywhere. With 40 hours of total battery life (8 hours per charge + 32 hours in case), premium 13mm drivers, and seamless Bluetooth 5.3 connectivity, every note comes alive. IPX5 water resistance means your music never stops, rain or shine. Touch controls, voice assistant support, and ergonomic design make these the last earbuds you\'ll ever need.', key_features: 'Active Noise Cancellation, 40-hour battery, Bluetooth 5.3, IPX5 water resistant, Touch controls', seo_keywords: 'wireless earbuds, noise cancelling earbuds, bluetooth earbuds, premium earbuds', status: 'published' },
      { product_name: 'EcoSmart Water Bottle', category: 'Lifestyle', short_description: 'Self-cleaning smart water bottle that tracks hydration and keeps drinks cold for 24 hours.', long_description: 'Stay hydrated the smart way with EcoSmart Water Bottle. This innovative bottle uses UV-C LED technology to purify water and clean itself every 2 hours. The integrated hydration tracker syncs with your phone to ensure you meet daily water goals. Triple-wall vacuum insulation keeps drinks cold for 24 hours or hot for 12 hours. Made from premium 18/8 stainless steel with a BPA-free lid, it\'s as good for the planet as it is for you. The sleek, modern design fits all standard cup holders.', key_features: 'UV-C self-cleaning, Hydration tracking app, 24hr cold/12hr hot, Stainless steel, BPA-free', seo_keywords: 'smart water bottle, self cleaning bottle, hydration tracker, insulated water bottle', status: 'published' },
      { product_name: 'CloudRest Memory Foam Pillow', category: 'Home & Living', short_description: 'Ergonomic cooling memory foam pillow for perfect spinal alignment and deep sleep.', long_description: 'Wake up refreshed with CloudRest Memory Foam Pillow. Our proprietary CoolFlow memory foam contours to your head and neck, providing optimal spinal alignment for back, side, and stomach sleepers. The breathable bamboo cover with cooling gel technology regulates temperature all night long. Hypoallergenic and dust mite resistant, it\'s perfect for allergy sufferers. The adjustable loft design lets you customize firmness by adding or removing foam. Experience hotel-quality sleep every night.', key_features: 'CoolFlow memory foam, Adjustable loft, Bamboo cover, Hypoallergenic, All sleep positions', seo_keywords: 'memory foam pillow, cooling pillow, ergonomic pillow, neck support pillow', status: 'published' },
      { product_name: 'FitTrack Pro Smartwatch', category: 'Electronics', short_description: 'Advanced fitness smartwatch with health monitoring, GPS, and 14-day battery life.', long_description: 'Take control of your health with FitTrack Pro Smartwatch. This comprehensive health companion monitors heart rate, blood oxygen, stress levels, and sleep quality 24/7. Built-in GPS tracks outdoor activities without your phone. With 100+ workout modes, swim-proof design to 50m, and smart notifications, it\'s your complete fitness partner. The always-on AMOLED display stays visible in any light. Incredible 14-day battery life means less charging, more living. Compatible with iOS and Android.', key_features: '14-day battery, GPS, Heart rate & SpO2, 100+ workout modes, 5ATM waterproof', seo_keywords: 'fitness smartwatch, health tracker, GPS watch, heart rate monitor watch', status: 'published' },
      { product_name: 'AeroGrind Coffee Maker', category: 'Kitchen', short_description: 'All-in-one coffee maker with built-in grinder and programmable brewing.', long_description: 'Elevate your morning ritual with AeroGrind Coffee Maker. This all-in-one machine features a precision conical burr grinder that grinds beans seconds before brewing for maximum freshness. Choose from 5 grind settings and 3 brew strengths to craft your perfect cup. The 12-cup thermal carafe keeps coffee hot for hours without a hot plate. Programmable 24-hour timer means fresh coffee is ready when you wake up. Easy-clean design with removable parts makes maintenance a breeze. Barista-quality coffee at home.', key_features: 'Built-in burr grinder, 5 grind settings, Thermal carafe, 24hr programmable, Auto-clean', seo_keywords: 'coffee maker with grinder, automatic coffee machine, programmable coffee maker', status: 'published' },
      { product_name: 'LuminaDesk LED Lamp', category: 'Office', short_description: 'Smart LED desk lamp with wireless charging, adjustable color temperature, and touch controls.', long_description: 'Illuminate your workspace with LuminaDesk LED Lamp. This sleek, modern lamp features adjustable color temperature (2700K-6500K) and 10 brightness levels to reduce eye strain and boost productivity. The built-in 15W wireless charging pad powers your devices while you work. Touch-sensitive controls and memory function remember your preferred settings. The flexible gooseneck and rotating head provide precise light positioning. Energy-efficient LEDs last 50,000 hours. Perfect for home offices, students, and professionals.', key_features: 'Adjustable color temp, Wireless charging, Touch controls, Flexible design, 50K hour LED', seo_keywords: 'LED desk lamp, wireless charging lamp, adjustable desk light, office lamp', status: 'published' },
      { product_name: 'TravelLite Carry-On Suitcase', category: 'Travel', short_description: 'Lightweight expandable carry-on with TSA lock, spinner wheels, and USB charging port.', long_description: 'Travel smarter with TravelLite Carry-On Suitcase. Weighing just 5.5 lbs, this ultra-lightweight luggage maximizes packing space while meeting all airline carry-on requirements. The durable polycarbonate shell resists scratches and impacts. Four 360° spinner wheels glide effortlessly in any direction. Built-in TSA-approved combination lock keeps belongings secure. The integrated USB port lets you charge devices on the go (power bank not included). Expandable design adds 20% more space when needed. Interior compression straps and mesh pockets keep everything organized.', key_features: 'Ultra-lightweight 5.5 lbs, TSA lock, Spinner wheels, USB port, Expandable', seo_keywords: 'carry on luggage, lightweight suitcase, spinner luggage, travel bag', status: 'published' },
      { product_name: 'ZenBreeze Air Purifier', category: 'Home & Living', short_description: 'HEPA air purifier for large rooms with smart sensors and whisper-quiet operation.', long_description: 'Breathe cleaner air with ZenBreeze Air Purifier. Our True HEPA H13 filter captures 99.97% of particles including dust, pollen, smoke, and pet dander down to 0.3 microns. Smart air quality sensors automatically adjust fan speed based on real-time pollution levels. The color-coded LED ring shows air quality at a glance. Whisper-quiet operation (24dB on low) won\'t disturb sleep. Covers rooms up to 1,500 sq ft with 5 air changes per hour. WiFi-enabled for app control and scheduling. Breathe easy, live better.', key_features: 'True HEPA H13, 1500 sq ft coverage, Smart sensors, 24dB quiet, WiFi app control', seo_keywords: 'HEPA air purifier, large room air purifier, smart air purifier, quiet air purifier', status: 'published' },
      { product_name: 'FlexFit Resistance Bands Set', category: 'Fitness', short_description: 'Complete resistance bands set with 5 levels, handles, ankle straps, and door anchor.', long_description: 'Transform any space into a gym with FlexFit Resistance Bands Set. This complete system includes 5 resistance levels (5-150 lbs total when combined), two cushioned handles, two ankle straps, and a door anchor. Made from premium natural latex with reinforced connections that won\'t snap. Stackable bands allow progressive resistance training for any fitness level. Includes carrying bag and exercise guide with 50+ workouts. Perfect for strength training, physical therapy, yoga, and pilates. Gym-quality workout anywhere.', key_features: '5 resistance levels, Premium latex, Handles & ankle straps, Door anchor, Carry bag', seo_keywords: 'resistance bands, workout bands, exercise bands set, home gym equipment', status: 'published' },
      { product_name: 'ChefMaster Digital Kitchen Scale', category: 'Kitchen', short_description: 'Precision digital kitchen scale with nutritional data and app connectivity.', long_description: 'Cook and bake with precision using ChefMaster Digital Kitchen Scale. The high-accuracy sensors measure from 1g to 11 lbs with 0.1g precision. Connect to our free app to access nutritional information for thousands of foods and track your daily intake. The sleek stainless steel platform is easy to clean and fingerprint-resistant. Tare function, unit conversion (g/oz/lb/ml), and low-battery indicator make cooking effortless. Slim design stores easily in any kitchen drawer. Take the guesswork out of cooking.', key_features: '0.1g precision, 11 lb capacity, Nutrition app, Stainless steel, Tare function', seo_keywords: 'digital kitchen scale, food scale, nutrition scale, precision scale', status: 'published' },
      { product_name: 'SoundSphere Portable Speaker', category: 'Electronics', short_description: '360° portable Bluetooth speaker with deep bass, waterproof design, and 20-hour playtime.', long_description: 'Music without boundaries. SoundSphere Portable Speaker delivers immersive 360° sound with surprisingly deep bass from its compact form. Dual passive radiators punch above their weight, filling any room with rich, balanced audio. IPX7 waterproof rating means pool parties, beach days, and shower concerts are all on the playlist. 20-hour battery life keeps the music playing all day and night. Pair two speakers for true stereo sound. Built-in microphone handles calls with clarity. Take your soundtrack everywhere.', key_features: '360° sound, IPX7 waterproof, 20-hour battery, Stereo pairing, Built-in mic', seo_keywords: 'portable bluetooth speaker, waterproof speaker, outdoor speaker, wireless speaker', status: 'draft' },
      { product_name: 'NightOwl Blue Light Glasses', category: 'Lifestyle', short_description: 'Stylish blue light blocking glasses that reduce eye strain from screens.', long_description: 'Protect your eyes in the digital age with NightOwl Blue Light Glasses. Our advanced lenses filter 40% of harmful blue light emitted by phones, computers, and tablets without distorting colors. Reduce eye strain, headaches, and sleep disruption from screen time. Lightweight, flexible frames fit comfortably for all-day wear. Anti-reflective and scratch-resistant coating ensures crystal-clear vision. Available in 6 modern styles to match any look. No prescription needed. Your eyes will thank you.', key_features: '40% blue light filter, Lightweight frames, Anti-reflective, Scratch-resistant, 6 styles', seo_keywords: 'blue light glasses, computer glasses, screen glasses, eye strain glasses', status: 'published' },
      { product_name: 'GrowSmart Indoor Garden', category: 'Home & Living', short_description: 'Automated indoor herb garden with LED grow lights and self-watering system.', long_description: 'Fresh herbs year-round with GrowSmart Indoor Garden. This intelligent growing system makes indoor gardening foolproof. Full-spectrum LED lights automatically cycle for optimal growth. The self-watering reservoir holds 2 weeks of water with low-level alerts. Grow up to 6 plants simultaneously in the included seed pods (basil, mint, and parsley starter kit included). No soil, no mess - just fresh herbs and vegetables at your fingertips. Compact countertop design fits any kitchen. From seed to harvest in 4-6 weeks.', key_features: 'Auto LED lighting, Self-watering, 6 plant capacity, Includes seed kit, Countertop size', seo_keywords: 'indoor garden, herb garden, hydroponic garden, indoor growing system', status: 'draft' },
      { product_name: 'SecureVault Password Manager', category: 'Software', short_description: 'Military-grade encrypted password manager with cross-platform sync and breach monitoring.', long_description: 'Never forget a password again. SecureVault Password Manager stores unlimited passwords with AES-256 encryption - the same standard used by governments. One master password unlocks all your accounts across unlimited devices. Auto-fill credentials instantly on any website or app. Dark web monitoring alerts you if your data appears in breaches. Secure password generator creates uncrackable passwords. Family plan covers up to 6 users with private vaults and secure sharing. Take control of your digital security today.', key_features: 'AES-256 encryption, Unlimited devices, Breach monitoring, Auto-fill, Family sharing', seo_keywords: 'password manager, secure password storage, password vault, password generator', status: 'published' },
      { product_name: 'ComfortStep Insoles', category: 'Lifestyle', short_description: 'Orthopedic gel insoles with arch support for all-day comfort and pain relief.', long_description: 'Walk in comfort all day with ComfortStep Insoles. Designed with podiatrists, these premium insoles feature dual-layer construction: shock-absorbing gel at the heel and ball, plus firm arch support for proper alignment. Reduce pain from plantar fasciitis, flat feet, and general foot fatigue. The antimicrobial top layer keeps feet fresh and odor-free. Trim-to-fit design works with any shoe type. Breathable materials prevent overheating. Replace worn shoe insoles and feel the difference from your first step.', key_features: 'Gel cushioning, Arch support, Antimicrobial, Trim-to-fit, All shoe types', seo_keywords: 'orthopedic insoles, gel insoles, arch support insoles, shoe inserts', status: 'published' }
    ];

    for (const product of productDescriptions) {
      await client.query(
        'INSERT INTO product_descriptions (user_id, product_name, category, short_description, long_description, key_features, seo_keywords, status) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)',
        [userId, product.product_name, product.category, product.short_description, product.long_description, product.key_features, product.seo_keywords, product.status]
      );
    }
    console.log('Product descriptions seeded: 15 items');

    // Seed Blog Posts (15 items)
    const blogPosts = [
      { title: '10 AI Marketing Trends That Will Dominate 2024', slug: 'ai-marketing-trends-2024', meta_description: 'Discover the top 10 AI marketing trends reshaping the industry in 2024. From predictive analytics to hyper-personalization.', content: 'Artificial intelligence is revolutionizing marketing at an unprecedented pace. As we move through 2024, several key trends are emerging that will define how brands connect with consumers.\n\n## 1. Hyper-Personalization at Scale\n\nAI now enables marketers to deliver truly personalized experiences to millions of customers simultaneously. Gone are the days of broad segmentation.\n\n## 2. Predictive Customer Journey Mapping\n\nMachine learning algorithms can now predict customer behavior with remarkable accuracy, allowing brands to anticipate needs before customers even express them.\n\n## 3. AI-Generated Creative Content\n\nFrom ad copy to social media posts, AI tools are creating high-quality content that rivals human creativity.\n\n[Continue with more trends...]', category: 'AI & Technology', tags: 'AI, Marketing Trends, 2024, Digital Marketing', word_count: 2500, seo_score: 92, status: 'published' },
      { title: 'The Complete Guide to Email Marketing Automation', slug: 'email-marketing-automation-guide', meta_description: 'Master email marketing automation with our comprehensive guide. Learn workflows, best practices, and tools.', content: 'Email marketing remains one of the highest-ROI channels available to marketers. When combined with automation, its power multiplies exponentially.\n\n## What is Email Marketing Automation?\n\nEmail marketing automation uses software to send targeted, timely emails based on specific triggers and customer behaviors.\n\n## Key Automation Workflows\n\n### Welcome Series\nThe first impression matters. A well-crafted welcome series can increase customer lifetime value by 33%.\n\n### Abandoned Cart Recovery\nRecover lost sales with strategic reminder emails. The average recovery rate is 10-15%.\n\n[Continue with more sections...]', category: 'Email Marketing', tags: 'Email, Automation, Marketing Guide, Workflows', word_count: 3200, seo_score: 88, status: 'published' },
      { title: 'How to Write Headlines That Convert', slug: 'headlines-that-convert', meta_description: 'Learn the psychology and formulas behind headlines that capture attention and drive conversions.', content: 'Your headline is the most important piece of copy you\'ll write. 80% of readers never make it past the headline.\n\n## The Psychology of Effective Headlines\n\nGreat headlines tap into fundamental human emotions: curiosity, fear, desire, and belonging.\n\n## Proven Headline Formulas\n\n### The "How To" Formula\nHow to [Achieve Desired Outcome] Without [Pain Point]\nExample: How to Lose Weight Without Giving Up Your Favorite Foods\n\n### The Number Formula\n[Number] Ways to [Achieve Goal]\nExample: 7 Ways to Double Your Email Open Rates\n\n[Continue with more formulas...]', category: 'Copywriting', tags: 'Headlines, Copywriting, Conversion, Writing Tips', word_count: 1800, seo_score: 95, status: 'published' },
      { title: 'Social Media Marketing Strategy for Small Businesses', slug: 'social-media-strategy-small-business', meta_description: 'A practical social media marketing strategy designed specifically for small businesses with limited resources.', content: 'Small businesses can\'t compete with enterprise marketing budgets. But they can win with smarter social media strategies.\n\n## Choosing the Right Platforms\n\nDon\'t try to be everywhere. Focus on 2-3 platforms where your audience actually spends time.\n\n### B2B Businesses\n- LinkedIn: Professional networking and thought leadership\n- Twitter: Industry conversations and news\n\n### B2C Businesses\n- Instagram: Visual storytelling and lifestyle content\n- TikTok: Reaching younger demographics\n\n[Continue with strategy details...]', category: 'Social Media', tags: 'Social Media, Small Business, Marketing Strategy', word_count: 2100, seo_score: 86, status: 'published' },
      { title: 'SEO Copywriting: The Ultimate Beginner\'s Guide', slug: 'seo-copywriting-beginners-guide', meta_description: 'Learn how to write content that ranks on Google and engages readers. Complete SEO copywriting guide for beginners.', content: 'SEO copywriting is the art of creating content that both search engines and humans love. It\'s not about keyword stuffing—it\'s about strategic, valuable content.\n\n## What is SEO Copywriting?\n\nSEO copywriting combines search engine optimization techniques with persuasive writing to create content that ranks and converts.\n\n## Keyword Research Fundamentals\n\nBefore writing a single word, understand what your audience is searching for.\n\n### Tools for Keyword Research\n- Google Keyword Planner (free)\n- Ahrefs (paid)\n- SEMrush (paid)\n\n[Continue with SEO techniques...]', category: 'SEO', tags: 'SEO, Copywriting, Content Marketing, Beginners Guide', word_count: 2800, seo_score: 91, status: 'published' },
      { title: 'The Psychology of Persuasion in Marketing', slug: 'psychology-persuasion-marketing', meta_description: 'Understand the psychological principles that make marketing messages irresistible. Based on Cialdini\'s research.', content: 'The most effective marketing doesn\'t feel like marketing. It taps into deep psychological principles that influence human behavior.\n\n## Cialdini\'s 6 Principles of Persuasion\n\n### 1. Reciprocity\nPeople feel obligated to return favors. Offer value first, and customers will want to reciprocate.\n\n### 2. Scarcity\nWe value things more when they\'re limited. "Only 3 left in stock" works because of this principle.\n\n### 3. Authority\nWe trust experts. Establish credibility through credentials, testimonials, and thought leadership.\n\n[Continue with more principles...]', category: 'Marketing Psychology', tags: 'Psychology, Persuasion, Consumer Behavior, Cialdini', word_count: 2400, seo_score: 89, status: 'published' },
      { title: 'Creating a Content Calendar That Works', slug: 'content-calendar-guide', meta_description: 'Build an effective content calendar that keeps your marketing consistent and stress-free. Templates included.', content: 'A content calendar transforms chaotic content creation into a systematic, manageable process.\n\n## Why You Need a Content Calendar\n\n- Consistency: Never miss a posting schedule\n- Quality: Plan ahead for better content\n- Collaboration: Align your team\n- Strategy: Connect content to business goals\n\n## Building Your Content Calendar\n\n### Step 1: Audit Existing Content\nBefore planning new content, understand what you already have.\n\n### Step 2: Define Content Pillars\nIdentify 3-5 core topics that align with your brand and audience interests.\n\n[Continue with calendar building...]', category: 'Content Marketing', tags: 'Content Calendar, Planning, Content Strategy, Templates', word_count: 1900, seo_score: 84, status: 'published' },
      { title: 'Facebook Ads vs Google Ads: Which is Right for Your Business?', slug: 'facebook-ads-vs-google-ads', meta_description: 'Compare Facebook Ads and Google Ads to determine which platform delivers better ROI for your specific business.', content: 'The Facebook vs Google ads debate doesn\'t have a one-size-fits-all answer. The right choice depends on your business, audience, and goals.\n\n## Understanding the Platforms\n\n### Google Ads: Intent-Based Advertising\nGoogle Ads captures people actively searching for solutions. High intent, but higher competition.\n\n### Facebook Ads: Interest-Based Advertising\nFacebook Ads reach people based on demographics and interests. Great for awareness and discovery.\n\n## When to Choose Google Ads\n\n- Your product solves a known problem\n- People are actively searching for your solution\n- You have a higher price point\n\n[Continue with comparison...]', category: 'Paid Advertising', tags: 'Facebook Ads, Google Ads, PPC, Advertising', word_count: 2200, seo_score: 87, status: 'published' },
      { title: 'Building a Brand Voice: A Step-by-Step Guide', slug: 'building-brand-voice-guide', meta_description: 'Develop a distinctive brand voice that resonates with your audience and sets you apart from competitors.', content: 'Your brand voice is how your company sounds across all communications. It\'s the personality that makes your brand memorable and relatable.\n\n## What is Brand Voice?\n\nBrand voice encompasses the tone, style, and personality expressed in your marketing communications.\n\n## Why Brand Voice Matters\n\n- Recognition: Consistent voice builds brand recognition\n- Trust: Authentic voice builds customer trust\n- Differentiation: Unique voice sets you apart\n\n## Defining Your Brand Voice\n\n### Step 1: Know Your Audience\nYour voice should resonate with the people you\'re trying to reach.\n\n[Continue with brand voice development...]', category: 'Branding', tags: 'Brand Voice, Branding, Marketing Strategy, Identity', word_count: 2000, seo_score: 85, status: 'published' },
      { title: 'Landing Page Optimization: 15 Proven Techniques', slug: 'landing-page-optimization-techniques', meta_description: 'Boost your landing page conversions with these 15 proven optimization techniques backed by data.', content: 'Your landing page is where conversions happen—or don\'t. Small optimizations can lead to massive improvements in results.\n\n## 1. Clear, Benefit-Focused Headlines\n\nYour headline should instantly communicate value. Focus on outcomes, not features.\n\n## 2. Single Call-to-Action\n\nMultiple CTAs create decision paralysis. One clear CTA outperforms every time.\n\n## 3. Social Proof Above the Fold\n\nShow testimonials, logos, or numbers before visitors scroll.\n\n## 4. Reduce Form Fields\n\nEvery additional field reduces conversions by approximately 11%.\n\n[Continue with more techniques...]', category: 'Conversion Optimization', tags: 'Landing Pages, CRO, Conversion Rate, Optimization', word_count: 2600, seo_score: 93, status: 'published' },
      { title: 'Video Marketing Statistics You Can\'t Ignore in 2024', slug: 'video-marketing-statistics-2024', meta_description: 'The latest video marketing statistics that prove why video should be central to your marketing strategy.', content: 'Video isn\'t just growing—it\'s dominating. These statistics show why video marketing is no longer optional.\n\n## Consumption Statistics\n\n- 82% of all internet traffic will be video by 2024\n- Average person watches 17 hours of video per week\n- YouTube is the second largest search engine\n\n## Marketing Impact Statistics\n\n- Video increases landing page conversions by 86%\n- Emails with video get 300% more clicks\n- Social video generates 1200% more shares than text and images combined\n\n## Platform Statistics\n\n[Continue with more statistics...]', category: 'Video Marketing', tags: 'Video, Statistics, Marketing Data, 2024', word_count: 1600, seo_score: 82, status: 'published' },
      { title: 'How to Conduct a Competitive Analysis for Marketing', slug: 'competitive-analysis-marketing', meta_description: 'Learn how to analyze your competitors\' marketing strategies and find opportunities to outperform them.', content: 'Understanding your competition is crucial for developing effective marketing strategies. Here\'s how to conduct a thorough competitive analysis.\n\n## Why Competitive Analysis Matters\n\n- Identify market gaps and opportunities\n- Learn from competitors\' successes and failures\n- Differentiate your positioning\n- Set realistic benchmarks\n\n## Step 1: Identify Your Competitors\n\n### Direct Competitors\nCompanies offering similar products to similar audiences.\n\n### Indirect Competitors\nCompanies solving the same problem with different solutions.\n\n[Continue with analysis methodology...]', category: 'Marketing Strategy', tags: 'Competitive Analysis, Strategy, Research, Market Analysis', word_count: 2300, seo_score: 86, status: 'draft' },
      { title: 'The Art of Writing Calls-to-Action That Convert', slug: 'writing-ctas-that-convert', meta_description: 'Master the art of writing compelling CTAs that drive clicks and conversions. Examples and formulas included.', content: 'Your call-to-action is the tipping point between bounce and conversion. Great CTAs don\'t just tell people what to do—they make them want to do it.\n\n## Anatomy of a High-Converting CTA\n\n### Action Verbs\nStart with strong action verbs: Get, Start, Join, Discover, Unlock\n\n### Value Proposition\nCommunicate what they\'ll get: "Get Your Free Guide" vs "Submit"\n\n### Urgency\nCreate time pressure: "Start Your Free Trial Today"\n\n## CTA Examples by Type\n\n### Lead Generation\n- "Download Your Free Checklist"\n- "Get Instant Access"\n\n[Continue with more examples...]', category: 'Copywriting', tags: 'CTA, Copywriting, Conversion, Best Practices', word_count: 1700, seo_score: 90, status: 'published' },
      { title: 'Influencer Marketing ROI: How to Measure Success', slug: 'influencer-marketing-roi', meta_description: 'Learn how to measure the true ROI of your influencer marketing campaigns with concrete metrics and formulas.', content: 'Influencer marketing spend is projected to reach $21 billion in 2024. But how do you know if it\'s actually working?\n\n## Defining Influencer Marketing ROI\n\nROI = (Revenue Generated - Campaign Cost) / Campaign Cost x 100\n\nBut revenue isn\'t the only metric that matters.\n\n## Key Metrics to Track\n\n### Awareness Metrics\n- Reach and impressions\n- Brand mention increase\n- Follower growth\n\n### Engagement Metrics\n- Likes, comments, shares\n- Engagement rate\n- Save rate\n\n[Continue with ROI calculation methods...]', category: 'Influencer Marketing', tags: 'Influencer Marketing, ROI, Metrics, Measurement', word_count: 2100, seo_score: 84, status: 'published' },
      { title: 'Email Subject Lines: 50 Templates That Get Opens', slug: 'email-subject-line-templates', meta_description: '50 proven email subject line templates organized by category. Copy, customize, and boost your open rates.', content: 'Your subject line determines whether your email gets opened or ignored. Here are 50 templates proven to drive opens.\n\n## Curiosity-Driven Subject Lines\n\n1. "You won\'t believe what happened next..."\n2. "The secret to [desired outcome] revealed"\n3. "What [industry experts] don\'t want you to know"\n\n## Urgency Subject Lines\n\n4. "Last chance: [offer] expires tonight"\n5. "Only [number] spots left"\n6. "[Hours] left to claim your [benefit]"\n\n## Personalization Subject Lines\n\n7. "[Name], you left something behind"\n8. "A special gift just for you, [Name]"\n\n[Continue with more templates...]', category: 'Email Marketing', tags: 'Email Subject Lines, Templates, Open Rates, Email Tips', word_count: 1500, seo_score: 91, status: 'draft' }
    ];

    for (const post of blogPosts) {
      await client.query(
        'INSERT INTO blog_posts (user_id, title, slug, meta_description, content, category, tags, word_count, seo_score, status) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)',
        [userId, post.title, post.slug, post.meta_description, post.content, post.category, post.tags, post.word_count, post.seo_score, post.status]
      );
    }
    console.log('Blog posts seeded: 15 items');

    // Seed Landing Pages (15 items)
    const landingPages = [
      { page_name: 'Free Trial Signup', headline: 'Start Creating Amazing Marketing Copy in Minutes', subheadline: 'Join 50,000+ marketers using AI to write better content faster. No credit card required.', body_content: 'Stop staring at blank pages. Our AI understands your brand voice and creates compelling copy that converts.\n\n✓ Generate ad copy in seconds\n✓ Write emails that get opened\n✓ Create social posts that engage\n✓ Craft product descriptions that sell\n\nTrusted by teams at Netflix, Spotify, and Shopify.', cta_text: 'Start Free Trial', cta_url: '/signup', conversion_rate: 12.5, status: 'published' },
      { page_name: 'Pro Plan Upgrade', headline: 'Unlock the Full Power of AI Marketing', subheadline: 'Upgrade to Pro and get unlimited generations, advanced features, and priority support.', body_content: 'Your free plan is just the beginning. Pro unlocks everything:\n\n★ Unlimited AI generations\n★ Advanced tone customization\n★ Team collaboration tools\n★ API access\n★ Priority support\n★ Custom brand voice training\n\nJoin 10,000+ Pro users who are creating at scale.', cta_text: 'Upgrade to Pro', cta_url: '/upgrade', conversion_rate: 8.3, status: 'published' },
      { page_name: 'Enterprise Demo', headline: 'AI Marketing at Enterprise Scale', subheadline: 'See how Fortune 500 companies are transforming their content operations with AI.', body_content: 'Enterprise features designed for large teams:\n\n• SSO and advanced security\n• Custom AI model training\n• Dedicated account manager\n• SLA guarantees\n• Unlimited team members\n• Custom integrations\n\nBook a personalized demo with our enterprise team.', cta_text: 'Book Demo', cta_url: '/demo', conversion_rate: 15.2, status: 'published' },
      { page_name: 'Black Friday Sale', headline: '50% Off All Annual Plans - Black Friday Only', subheadline: 'Our biggest sale of the year. Lock in savings for the next 12 months.', body_content: '🔥 BLACK FRIDAY SPECIAL 🔥\n\nThis is NOT a drill. Get 50% off any annual plan.\n\nStarter: $99/year (was $199)\nPro: $249/year (was $499)\nTeam: $499/year (was $999)\n\nOffer expires Monday at midnight. No extensions.', cta_text: 'Claim 50% Off', cta_url: '/black-friday', conversion_rate: 24.7, status: 'published' },
      { page_name: 'Webinar Registration', headline: 'Free Masterclass: 10X Your Marketing with AI', subheadline: 'Learn the exact strategies top marketers use to create content 10x faster.', body_content: 'Join us for an exclusive 60-minute masterclass:\n\n📅 Date: February 15, 2024\n⏰ Time: 2:00 PM EST\n👤 Host: Sarah Johnson, CMO\n\nWhat you\'ll learn:\n• AI prompting secrets for better copy\n• Workflow automation strategies\n• Real case studies from top brands\n• Live Q&A session\n\nLimited to 500 attendees.', cta_text: 'Reserve My Seat', cta_url: '/webinar', conversion_rate: 32.1, status: 'published' },
      { page_name: 'Case Study Download', headline: 'How Startup X Grew Revenue 300% with AI Copy', subheadline: 'Get the full case study with exact strategies, templates, and results.', body_content: 'Inside this case study:\n\n📈 The challenge: Scaling content with a small team\n💡 The solution: AI-powered content workflow\n🎯 The results: 300% revenue growth in 6 months\n\nPlus: The exact prompts and templates they used.\n\nDownload the complete 15-page case study free.', cta_text: 'Download Case Study', cta_url: '/case-study', conversion_rate: 18.9, status: 'published' },
      { page_name: 'Affiliate Program', headline: 'Earn 30% Recurring Commission', subheadline: 'Join our affiliate program and get paid for every customer you refer.', body_content: 'Partner with AI Marketing and earn passive income:\n\n💰 30% recurring commission\n🔄 Lifetime customer attribution\n📊 Real-time tracking dashboard\n🎨 Marketing materials provided\n💳 Monthly payouts via PayPal\n\nTop affiliates earn $5,000+ per month.', cta_text: 'Join Affiliate Program', cta_url: '/affiliates', conversion_rate: 6.8, status: 'published' },
      { page_name: 'Agency Partner', headline: 'White-Label AI Marketing for Agencies', subheadline: 'Offer AI-powered content services to your clients under your brand.', body_content: 'Built for agencies:\n\n• White-label platform with your branding\n• Unlimited client workspaces\n• Bulk pricing discounts\n• Dedicated partner manager\n• Co-marketing opportunities\n• Priority feature requests\n\nJoin 200+ agencies already partnering with us.', cta_text: 'Apply for Partnership', cta_url: '/partners', conversion_rate: 11.4, status: 'published' },
      { page_name: 'Feature: Email Generator', headline: 'Write Emails That Actually Get Opened', subheadline: 'Our AI email generator creates subject lines with 2x higher open rates.', body_content: 'Stop sending emails that go unread.\n\nOur email AI understands:\n• Your audience segments\n• Optimal send times\n• Subject line psychology\n• Personalization at scale\n\nGenerate complete email campaigns in minutes:\n✓ Subject lines\n✓ Preview text\n✓ Body copy\n✓ CTAs\n\nAverage open rate improvement: 47%', cta_text: 'Try Email Generator', cta_url: '/features/email', conversion_rate: 9.7, status: 'published' },
      { page_name: 'Feature: Ad Copy', headline: 'Create High-Converting Ad Copy Instantly', subheadline: 'Generate scroll-stopping ads for Facebook, Google, LinkedIn, and more.', body_content: 'Ads that actually convert:\n\nOur AI is trained on millions of high-performing ads across:\n• Facebook & Instagram\n• Google Ads\n• LinkedIn\n• TikTok\n• Twitter\n\nJust enter your product and audience. Get multiple ad variations in seconds.\n\nAverage CTR improvement: 34%', cta_text: 'Create Ads Now', cta_url: '/features/ads', conversion_rate: 10.2, status: 'published' },
      { page_name: 'Comparison: vs Jasper', headline: 'AI Marketing vs Jasper: Honest Comparison', subheadline: 'See how we stack up against Jasper on features, pricing, and results.', body_content: 'We\'ll be honest about the differences:\n\n| Feature | AI Marketing | Jasper |\n|---------|-------------|--------|\n| Price | $29/mo | $49/mo |\n| Generations | Unlimited | Limited |\n| Templates | 100+ | 50+ |\n| Team Features | Included | Extra |\n\nBoth are great tools. Here\'s who should choose us...', cta_text: 'Start Free Trial', cta_url: '/vs-jasper', conversion_rate: 14.3, status: 'published' },
      { page_name: 'Pricing Page', headline: 'Simple, Transparent Pricing', subheadline: 'No hidden fees. No surprises. Cancel anytime.', body_content: 'Choose the plan that fits your needs:\n\n**Starter - $29/mo**\n• 50 AI generations/month\n• All templates\n• Email support\n\n**Pro - $49/mo**\n• Unlimited generations\n• Advanced features\n• Priority support\n\n**Team - $99/mo**\n• Everything in Pro\n• 5 team members\n• Collaboration tools\n\nAll plans include a 14-day free trial.', cta_text: 'View Full Pricing', cta_url: '/pricing', conversion_rate: 7.6, status: 'published' },
      { page_name: 'Lead Magnet: Prompt Guide', headline: 'Free: 100 AI Prompts for Marketers', subheadline: 'The ultimate prompt library for creating better marketing content with AI.', body_content: 'Download our free prompt guide:\n\n📝 25 prompts for ad copy\n📧 25 prompts for emails\n📱 25 prompts for social media\n📄 25 prompts for long-form content\n\nThese are the exact prompts our team uses daily.\n\nNo fluff. Just prompts that work.', cta_text: 'Get Free Prompts', cta_url: '/prompts', conversion_rate: 28.5, status: 'published' },
      { page_name: 'ROI Calculator', headline: 'Calculate Your AI Marketing ROI', subheadline: 'See exactly how much time and money you could save with AI content creation.', body_content: 'Enter your current content metrics:\n\n• Hours spent on content weekly\n• Average hourly rate\n• Content pieces created monthly\n• Current conversion rate\n\nOur calculator shows:\n✓ Time saved per month\n✓ Cost savings\n✓ Projected conversion lift\n✓ Total ROI\n\nMost teams see 10x ROI in the first month.', cta_text: 'Calculate My ROI', cta_url: '/roi', conversion_rate: 19.8, status: 'draft' },
      { page_name: 'Customer Success Stories', headline: 'Real Results from Real Customers', subheadline: 'See how businesses like yours are winning with AI marketing.', body_content: '"AI Marketing helped us 10x our content output without hiring." - Tech Startup CEO\n\n"We reduced our cost per lead by 60% using AI ad copy." - E-commerce Director\n\n"Our email open rates jumped from 18% to 34%." - Marketing Manager\n\nRead their full stories and discover what\'s possible for your business.', cta_text: 'Read Success Stories', cta_url: '/stories', conversion_rate: 13.1, status: 'published' }
    ];

    for (const page of landingPages) {
      await client.query(
        'INSERT INTO landing_pages (user_id, page_name, headline, subheadline, body_content, cta_text, cta_url, conversion_rate, status) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)',
        [userId, page.page_name, page.headline, page.subheadline, page.body_content, page.cta_text, page.cta_url, page.conversion_rate, page.status]
      );
    }
    console.log('Landing pages seeded: 15 items');

    // Seed Taglines (15 items)
    const taglines = [
      { brand_name: 'AI Marketing', tagline: 'Write Better. Faster. Smarter.', category: 'SaaS', style: 'Powerful', is_favorite: true, status: 'active' },
      { brand_name: 'AI Marketing', tagline: 'Your AI Marketing Partner', category: 'SaaS', style: 'Friendly', is_favorite: false, status: 'active' },
      { brand_name: 'AI Marketing', tagline: 'Marketing Copy That Converts', category: 'SaaS', style: 'Results-focused', is_favorite: true, status: 'active' },
      { brand_name: 'EcoLife', tagline: 'Sustainable Living Made Simple', category: 'Lifestyle', style: 'Approachable', is_favorite: false, status: 'active' },
      { brand_name: 'EcoLife', tagline: 'Good for You. Better for Earth.', category: 'Lifestyle', style: 'Inspiring', is_favorite: true, status: 'active' },
      { brand_name: 'TechFlow', tagline: 'Innovation Without Complexity', category: 'Technology', style: 'Professional', is_favorite: false, status: 'active' },
      { brand_name: 'TechFlow', tagline: 'The Future of Work, Today', category: 'Technology', style: 'Bold', is_favorite: true, status: 'active' },
      { brand_name: 'FitPro', tagline: 'Transform Your Body. Transform Your Life.', category: 'Fitness', style: 'Motivational', is_favorite: true, status: 'active' },
      { brand_name: 'FitPro', tagline: 'Every Rep Counts', category: 'Fitness', style: 'Energetic', is_favorite: false, status: 'active' },
      { brand_name: 'CloudBank', tagline: 'Banking That Moves With You', category: 'Finance', style: 'Modern', is_favorite: true, status: 'active' },
      { brand_name: 'CloudBank', tagline: 'Your Money, Your Rules', category: 'Finance', style: 'Empowering', is_favorite: false, status: 'active' },
      { brand_name: 'FreshBite', tagline: 'Taste the Difference', category: 'Food & Beverage', style: 'Sensory', is_favorite: false, status: 'active' },
      { brand_name: 'FreshBite', tagline: 'From Farm to Table in 24 Hours', category: 'Food & Beverage', style: 'Authentic', is_favorite: true, status: 'active' },
      { brand_name: 'SafeGuard', tagline: 'Protection You Can Trust', category: 'Security', style: 'Reassuring', is_favorite: true, status: 'active' },
      { brand_name: 'SafeGuard', tagline: 'Sleep Better Knowing We\'re Watching', category: 'Security', style: 'Comforting', is_favorite: false, status: 'active' }
    ];

    for (const tagline of taglines) {
      await client.query(
        'INSERT INTO taglines (user_id, brand_name, tagline, category, style, is_favorite, status) VALUES ($1, $2, $3, $4, $5, $6, $7)',
        [userId, tagline.brand_name, tagline.tagline, tagline.category, tagline.style, tagline.is_favorite, tagline.status]
      );
    }
    console.log('Taglines seeded: 15 items');

    // Seed SEO Content (15 items)
    const seoContent = [
      { page_url: '/features/ai-copywriting', meta_title: 'AI Copywriting Tool | Generate Marketing Copy in Seconds', meta_description: 'Create compelling ad copy, emails, and social posts with our AI copywriting tool. Join 50,000+ marketers. Start free trial today.', focus_keyword: 'AI copywriting tool', secondary_keywords: 'AI copy generator, marketing copy AI, automated copywriting', seo_score: 94, status: 'active' },
      { page_url: '/features/email-generator', meta_title: 'AI Email Generator | Write Emails That Get Opened', meta_description: 'Generate high-converting email campaigns with AI. Subject lines, body copy, and CTAs. Boost open rates by 47%. Try free.', focus_keyword: 'AI email generator', secondary_keywords: 'email copy AI, email subject line generator, email marketing AI', seo_score: 91, status: 'active' },
      { page_url: '/features/ad-copy', meta_title: 'AI Ad Copy Generator | Create Ads for Facebook, Google & More', meta_description: 'Generate scroll-stopping ad copy for all platforms. Trained on millions of high-performing ads. Increase CTR by 34%. Free trial.', focus_keyword: 'AI ad copy generator', secondary_keywords: 'Facebook ad copy AI, Google ads generator, ad copywriting tool', seo_score: 89, status: 'active' },
      { page_url: '/pricing', meta_title: 'Pricing Plans | AI Marketing - Start Free, Scale Affordably', meta_description: 'Simple, transparent pricing. Free trial, no credit card required. Plans starting at $29/mo. Unlimited generations on Pro.', focus_keyword: 'AI marketing pricing', secondary_keywords: 'AI copywriting cost, marketing AI plans, content AI pricing', seo_score: 86, status: 'active' },
      { page_url: '/blog/ai-marketing-trends', meta_title: '10 AI Marketing Trends Dominating 2024 | AI Marketing Blog', meta_description: 'Discover the AI marketing trends reshaping the industry. From hyper-personalization to predictive analytics. Read now.', focus_keyword: 'AI marketing trends 2024', secondary_keywords: 'marketing AI trends, artificial intelligence marketing, AI in advertising', seo_score: 92, status: 'active' },
      { page_url: '/use-cases/ecommerce', meta_title: 'AI Marketing for E-commerce | Product Descriptions & More', meta_description: 'Generate product descriptions, email campaigns, and ad copy for your online store. Increase conversions by 25%. Start free.', focus_keyword: 'AI marketing ecommerce', secondary_keywords: 'product description generator, ecommerce AI copywriting', seo_score: 88, status: 'active' },
      { page_url: '/use-cases/agencies', meta_title: 'AI Marketing for Agencies | White-Label Content Solution', meta_description: 'Scale your agency content output 10x. White-label platform, unlimited clients, bulk pricing. Partner with us today.', focus_keyword: 'AI marketing agencies', secondary_keywords: 'white label AI copywriting, agency content tools', seo_score: 85, status: 'active' },
      { page_url: '/integrations', meta_title: 'Integrations | Connect AI Marketing to Your Favorite Tools', meta_description: 'Integrate with HubSpot, Mailchimp, WordPress, Shopify, and 50+ more. Seamless workflow automation. See all integrations.', focus_keyword: 'AI marketing integrations', secondary_keywords: 'marketing tool integrations, AI content integrations', seo_score: 83, status: 'active' },
      { page_url: '/about', meta_title: 'About AI Marketing | Our Mission to Democratize Great Copy', meta_description: 'Learn about our mission to make professional marketing copy accessible to everyone. Meet the team behind AI Marketing.', focus_keyword: 'about AI Marketing', secondary_keywords: 'AI Marketing company, marketing AI startup', seo_score: 78, status: 'active' },
      { page_url: '/resources/templates', meta_title: '100+ Free Marketing Templates | AI Marketing Resources', meta_description: 'Download free marketing templates for emails, ads, social media, and more. Created by experts, powered by AI. Get templates.', focus_keyword: 'marketing templates', secondary_keywords: 'free marketing templates, email templates, ad templates', seo_score: 90, status: 'active' },
      { page_url: '/careers', meta_title: 'Careers at AI Marketing | Join Our Growing Team', meta_description: 'Build the future of marketing with us. Open positions in engineering, marketing, and customer success. Remote-friendly.', focus_keyword: 'AI Marketing careers', secondary_keywords: 'marketing AI jobs, AI startup jobs', seo_score: 72, status: 'active' },
      { page_url: '/contact', meta_title: 'Contact Us | AI Marketing Support & Sales', meta_description: 'Get in touch with our team. Customer support, sales inquiries, and partnerships. Response within 24 hours guaranteed.', focus_keyword: 'contact AI Marketing', secondary_keywords: 'AI Marketing support, marketing AI help', seo_score: 75, status: 'active' },
      { page_url: '/blog/email-marketing-guide', meta_title: 'Complete Email Marketing Automation Guide 2024 | AI Marketing', meta_description: 'Master email marketing automation. Learn workflows, best practices, and tools. Free guide with templates included.', focus_keyword: 'email marketing automation guide', secondary_keywords: 'email automation, marketing automation tips', seo_score: 93, status: 'active' },
      { page_url: '/comparison/jasper', meta_title: 'AI Marketing vs Jasper | Honest Feature & Pricing Comparison', meta_description: 'Compare AI Marketing and Jasper side-by-side. Features, pricing, pros and cons. Find the right tool for your needs.', focus_keyword: 'AI Marketing vs Jasper', secondary_keywords: 'Jasper alternative, AI copywriting comparison', seo_score: 87, status: 'active' },
      { page_url: '/features/social-media', meta_title: 'AI Social Media Post Generator | Create Viral Content', meta_description: 'Generate engaging social media posts for Instagram, Twitter, LinkedIn, and TikTok. Hashtags included. Try free today.', focus_keyword: 'AI social media generator', secondary_keywords: 'social post AI, Instagram caption generator', seo_score: 91, status: 'active' }
    ];

    for (const seo of seoContent) {
      await client.query(
        'INSERT INTO seo_content (user_id, page_url, meta_title, meta_description, focus_keyword, secondary_keywords, seo_score, status) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)',
        [userId, seo.page_url, seo.meta_title, seo.meta_description, seo.focus_keyword, seo.secondary_keywords, seo.seo_score, seo.status]
      );
    }
    console.log('SEO content seeded: 15 items');

    // Seed Press Releases (15 items)
    const pressReleases = [
      { headline: 'AI Marketing Raises $50M Series B to Accelerate AI-Powered Content Creation', subheadline: 'Investment led by Sequoia Capital will fund product development and global expansion', dateline: 'SAN FRANCISCO, February 15, 2024', body: 'AI Marketing, the leading AI-powered content creation platform, today announced it has raised $50 million in Series B funding led by Sequoia Capital, with participation from existing investors Andreessen Horowitz and Y Combinator.\n\nThe funding will be used to accelerate product development, expand the team, and enter new international markets.\n\n"This investment validates our vision of making professional marketing copy accessible to every business," said John Smith, CEO of AI Marketing. "We\'re just getting started."', boilerplate: 'AI Marketing is the leading AI-powered content creation platform, helping over 50,000 businesses create compelling marketing copy in seconds.', contact_info: 'Media Contact: press@aimarketing.com', status: 'published' },
      { headline: 'AI Marketing Launches Revolutionary Video Script Generator', subheadline: 'New feature enables marketers to create professional video scripts in minutes', dateline: 'SAN FRANCISCO, February 10, 2024', body: 'AI Marketing today announced the launch of its highly anticipated Video Script Generator, a new AI-powered tool that enables marketers to create professional video scripts for YouTube, TikTok, commercials, and more.\n\nThe new feature uses advanced language models trained on thousands of high-performing video scripts to generate engaging content tailored to each platform\'s unique requirements.\n\n"Video is the future of marketing, and creating scripts has always been a bottleneck," said Jane Doe, VP of Product. "Our Video Script Generator removes that barrier."', boilerplate: 'AI Marketing is the leading AI-powered content creation platform, helping over 50,000 businesses create compelling marketing copy in seconds.', contact_info: 'Media Contact: press@aimarketing.com', status: 'published' },
      { headline: 'AI Marketing Surpasses 100,000 Users Milestone', subheadline: 'Platform doubles user base in just six months', dateline: 'SAN FRANCISCO, February 5, 2024', body: 'AI Marketing today announced it has surpassed 100,000 users, doubling its user base in just six months. The milestone reflects growing demand for AI-powered content creation tools among businesses of all sizes.\n\nThe platform has generated over 10 million pieces of marketing content since launch, including ad copy, emails, social media posts, and product descriptions.\n\n"Reaching 100,000 users is an incredible milestone, but what excites us most is the impact we\'re having on businesses," said John Smith, CEO.', boilerplate: 'AI Marketing is the leading AI-powered content creation platform, helping over 100,000 businesses create compelling marketing copy in seconds.', contact_info: 'Media Contact: press@aimarketing.com', status: 'published' },
      { headline: 'AI Marketing Named to Forbes AI 50 List', subheadline: 'Recognition highlights company\'s innovation in marketing technology', dateline: 'SAN FRANCISCO, January 28, 2024', body: 'AI Marketing has been named to the Forbes AI 50 list, an annual ranking of the most promising artificial intelligence companies in the world.\n\nThe selection recognizes AI Marketing\'s innovative approach to content creation and its rapid growth in the marketing technology sector.\n\n"Being recognized by Forbes alongside some of the most innovative AI companies in the world is an honor," said John Smith, CEO. "This recognition belongs to our entire team and the customers who inspire us."', boilerplate: 'AI Marketing is the leading AI-powered content creation platform, helping over 100,000 businesses create compelling marketing copy in seconds.', contact_info: 'Media Contact: press@aimarketing.com', status: 'published' },
      { headline: 'AI Marketing Partners with HubSpot for Seamless Integration', subheadline: 'New integration brings AI content creation directly into HubSpot workflows', dateline: 'SAN FRANCISCO, January 20, 2024', body: 'AI Marketing today announced a strategic partnership with HubSpot, integrating its AI content creation capabilities directly into the HubSpot marketing platform.\n\nThe integration allows HubSpot users to generate AI-powered marketing copy without leaving their existing workflow, streamlining content creation and improving productivity.\n\n"This partnership brings the power of AI content creation to millions of HubSpot users," said Jane Doe, VP of Partnerships.', boilerplate: 'AI Marketing is the leading AI-powered content creation platform, helping over 100,000 businesses create compelling marketing copy in seconds.', contact_info: 'Media Contact: press@aimarketing.com', status: 'published' },
      { headline: 'AI Marketing Expands to European Market with UK Office', subheadline: 'New London office will serve growing European customer base', dateline: 'LONDON, January 15, 2024', body: 'AI Marketing today announced the opening of its first European office in London, marking a significant milestone in the company\'s global expansion strategy.\n\nThe new office will serve the company\'s rapidly growing European customer base and support localization efforts for additional languages.\n\n"Europe represents a massive opportunity for AI Marketing," said John Smith, CEO. "Our London office will help us better serve our European customers and partners."', boilerplate: 'AI Marketing is the leading AI-powered content creation platform, helping over 100,000 businesses create compelling marketing copy in seconds.', contact_info: 'Media Contact: press@aimarketing.com', status: 'published' },
      { headline: 'AI Marketing Introduces Enterprise Plan with Advanced Security Features', subheadline: 'New tier designed for large organizations with strict compliance requirements', dateline: 'SAN FRANCISCO, January 10, 2024', body: 'AI Marketing today launched its Enterprise Plan, a new offering designed for large organizations with advanced security, compliance, and customization needs.\n\nThe Enterprise Plan includes SSO integration, SOC 2 compliance, custom AI model training, dedicated support, and SLA guarantees.\n\n"Enterprise customers have unique requirements, and our new plan addresses them all," said Jane Doe, VP of Product.', boilerplate: 'AI Marketing is the leading AI-powered content creation platform, helping over 100,000 businesses create compelling marketing copy in seconds.', contact_info: 'Media Contact: press@aimarketing.com', status: 'published' },
      { headline: 'AI Marketing Achieves SOC 2 Type II Certification', subheadline: 'Certification demonstrates commitment to data security and privacy', dateline: 'SAN FRANCISCO, January 5, 2024', body: 'AI Marketing today announced it has achieved SOC 2 Type II certification, demonstrating its commitment to maintaining the highest standards of data security and privacy.\n\nThe certification, issued after a rigorous third-party audit, validates the company\'s security controls, availability, and confidentiality practices.\n\n"Security is foundational to everything we do," said John Smith, CEO. "This certification gives our customers confidence that their data is protected."', boilerplate: 'AI Marketing is the leading AI-powered content creation platform, helping over 100,000 businesses create compelling marketing copy in seconds.', contact_info: 'Media Contact: press@aimarketing.com', status: 'published' },
      { headline: 'AI Marketing Releases 2024 State of AI in Marketing Report', subheadline: 'Annual report reveals key trends and adoption rates across industries', dateline: 'SAN FRANCISCO, December 20, 2023', body: 'AI Marketing today released its 2024 State of AI in Marketing report, revealing key insights into how businesses are adopting AI for content creation and marketing.\n\nKey findings include:\n- 78% of marketers plan to increase AI tool usage in 2024\n- AI-generated content performs 23% better on average\n- Email and ad copy are the top use cases\n\nThe full report is available for free download.', boilerplate: 'AI Marketing is the leading AI-powered content creation platform, helping over 100,000 businesses create compelling marketing copy in seconds.', contact_info: 'Media Contact: press@aimarketing.com', status: 'published' },
      { headline: 'AI Marketing Launches Affiliate Program with 30% Recurring Commission', subheadline: 'New program enables partners to earn passive income', dateline: 'SAN FRANCISCO, December 15, 2023', body: 'AI Marketing today launched its Affiliate Program, offering partners 30% recurring commission on all referred customers.\n\nThe program includes marketing materials, real-time tracking, and dedicated affiliate support. Payouts are made monthly via PayPal.\n\n"Our affiliates are key to our growth, and we\'re excited to reward their efforts," said Jane Doe, VP of Marketing.', boilerplate: 'AI Marketing is the leading AI-powered content creation platform, helping over 100,000 businesses create compelling marketing copy in seconds.', contact_info: 'Media Contact: press@aimarketing.com', status: 'published' },
      { headline: 'AI Marketing Wins TechCrunch Disrupt Startup Battlefield', subheadline: 'Company takes top prize at prestigious startup competition', dateline: 'SAN FRANCISCO, December 10, 2023', body: 'AI Marketing has won the TechCrunch Disrupt Startup Battlefield competition, taking home the top prize of $100,000 and the coveted Disrupt Cup.\n\nThe company was selected from over 200 applicants and competed against 20 finalists in front of expert judges and a live audience.\n\n"Winning Startup Battlefield is a dream come true," said John Smith, CEO. "This validation motivates us to work even harder for our customers."', boilerplate: 'AI Marketing is the leading AI-powered content creation platform, helping over 100,000 businesses create compelling marketing copy in seconds.', contact_info: 'Media Contact: press@aimarketing.com', status: 'published' },
      { headline: 'AI Marketing Introduces Multi-Language Support for Global Marketers', subheadline: 'Platform now supports content generation in 25 languages', dateline: 'SAN FRANCISCO, December 5, 2023', body: 'AI Marketing today announced multi-language support, enabling users to generate marketing content in 25 languages including Spanish, French, German, Portuguese, Japanese, and Chinese.\n\nThe feature uses advanced translation models to ensure content maintains its persuasive quality across languages.\n\n"Marketing is global, and now AI Marketing is too," said Jane Doe, VP of Product.', boilerplate: 'AI Marketing is the leading AI-powered content creation platform, helping over 100,000 businesses create compelling marketing copy in seconds.', contact_info: 'Media Contact: press@aimarketing.com', status: 'published' },
      { headline: 'AI Marketing Appoints Former Google Executive as Chief Technology Officer', subheadline: 'Industry veteran brings 20 years of AI and machine learning expertise', dateline: 'SAN FRANCISCO, November 28, 2023', body: 'AI Marketing today announced the appointment of Dr. Sarah Chen as Chief Technology Officer. Dr. Chen joins from Google, where she led AI initiatives for Google Ads.\n\nWith over 20 years of experience in AI and machine learning, Dr. Chen will lead AI Marketing\'s technical strategy and product innovation.\n\n"I\'m thrilled to join AI Marketing at such an exciting time," said Dr. Chen. "The opportunity to shape the future of AI-powered marketing is incredible."', boilerplate: 'AI Marketing is the leading AI-powered content creation platform, helping over 100,000 businesses create compelling marketing copy in seconds.', contact_info: 'Media Contact: press@aimarketing.com', status: 'published' },
      { headline: 'AI Marketing Launches Free Plan to Democratize AI Content Creation', subheadline: 'New tier makes AI marketing tools accessible to everyone', dateline: 'SAN FRANCISCO, November 20, 2023', body: 'AI Marketing today announced the launch of its Free Plan, making AI-powered content creation accessible to businesses and individuals at no cost.\n\nThe Free Plan includes 10 AI generations per month, access to all content templates, and basic analytics.\n\n"Every business deserves access to great marketing copy, regardless of budget," said John Smith, CEO. "Our Free Plan removes the barrier to entry."', boilerplate: 'AI Marketing is the leading AI-powered content creation platform, helping over 100,000 businesses create compelling marketing copy in seconds.', contact_info: 'Media Contact: press@aimarketing.com', status: 'published' },
      { headline: 'AI Marketing Raises $10M Seed Round to Build AI-Powered Marketing Platform', subheadline: 'Investment led by Andreessen Horowitz and Y Combinator', dateline: 'SAN FRANCISCO, November 15, 2023', body: 'AI Marketing today announced it has raised $10 million in seed funding led by Andreessen Horowitz and Y Combinator to build its AI-powered marketing content platform.\n\nThe company will use the funding to expand its engineering team and accelerate product development.\n\n"This investment allows us to build the marketing tool we always wished existed," said John Smith, CEO and co-founder.', boilerplate: 'AI Marketing is an AI-powered content creation platform that helps businesses create compelling marketing copy in seconds.', contact_info: 'Media Contact: press@aimarketing.com', status: 'draft' }
    ];

    for (const pr of pressReleases) {
      await client.query(
        'INSERT INTO press_releases (user_id, headline, subheadline, dateline, body, boilerplate, contact_info, status) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)',
        [userId, pr.headline, pr.subheadline, pr.dateline, pr.body, pr.boilerplate, pr.contact_info, pr.status]
      );
    }
    console.log('Press releases seeded: 15 items');

    // Seed Video Scripts (15 items)
    const videoScripts = [
      { title: 'Product Launch Announcement', video_type: 'YouTube', duration_seconds: 120, script_content: '[HOOK - 0:00-0:05]\nWhat if I told you that creating marketing copy just got 10x faster?\n\n[INTRO - 0:05-0:20]\nHey everyone! Today we\'re launching something we\'ve been working on for months, and I genuinely think it\'s going to change how you create marketing content forever.\n\n[PROBLEM - 0:20-0:40]\nWe\'ve all been there. Staring at a blank page, trying to write the perfect ad copy or email. It takes hours, sometimes days. And even then, you\'re never sure if it\'ll convert.\n\n[SOLUTION - 0:40-1:20]\nThat\'s why we built AI Marketing. Just tell our AI what you\'re selling and who you\'re selling to, and it generates compelling copy in seconds. Ad copy, emails, social posts, product descriptions - all optimized for conversion.\n\n[CTA - 1:20-2:00]\nReady to try it? Click the link below to start your free trial. No credit card required. And if you found this helpful, smash that like button and subscribe for more marketing tips!', visual_notes: 'Split screen showing frustrated marketer vs. happy AI Marketing user. Show product demo. End with logo and CTA overlay.', voiceover_text: 'Professional, energetic male voice. Conversational tone.', status: 'published' },
      { title: '30-Second Facebook Ad', video_type: 'Facebook Ad', duration_seconds: 30, script_content: '[0:00-0:03]\nTired of spending hours on marketing copy?\n\n[0:03-0:10]\nMeet AI Marketing - your AI copywriting assistant that creates compelling content in seconds.\n\n[0:10-0:20]\nAd copy, emails, social posts - all optimized for conversion. Used by 50,000+ marketers.\n\n[0:20-0:30]\nStart your free trial today. Link below.', visual_notes: 'Fast-paced cuts. Show typing animation, then instant results. Testimonial snippets. End with app interface and CTA.', voiceover_text: 'Upbeat female voice. Fast but clear.', status: 'published' },
      { title: 'Customer Testimonial Compilation', video_type: 'YouTube', duration_seconds: 180, script_content: '[INTRO - 0:00-0:15]\nDon\'t just take our word for it. Here\'s what real customers are saying about AI Marketing.\n\n[TESTIMONIAL 1 - 0:15-0:45]\n"Before AI Marketing, I spent 3-4 hours writing each email campaign. Now it takes me 15 minutes. The quality is incredible." - Sarah, E-commerce Owner\n\n[TESTIMONIAL 2 - 0:45-1:15]\n"We increased our ad CTR by 40% using AI-generated copy. It\'s like having a professional copywriter on demand." - Mike, Marketing Director\n\n[TESTIMONIAL 3 - 1:15-1:45]\n"As a small business owner, I couldn\'t afford a copywriter. AI Marketing leveled the playing field for me." - Lisa, Bakery Owner\n\n[TESTIMONIAL 4 - 1:45-2:15]\n"The ROI is insane. We saved $50,000 in copywriting costs last year alone." - David, Agency CEO\n\n[CTA - 2:15-3:00]\nJoin 50,000+ marketers creating better content faster. Start your free trial at aimarketing.com.', visual_notes: 'Interview-style shots of each customer. B-roll of them using the product. Metrics/results on screen.', voiceover_text: 'Warm, trustworthy narrator voice between testimonials.', status: 'published' },
      { title: 'TikTok Product Demo', video_type: 'TikTok', duration_seconds: 60, script_content: '[0:00-0:03]\n POV: You need ad copy in 5 minutes\n\n[0:03-0:10]\n*Opens AI Marketing*\n*Types: "Facebook ad for running shoes, target: fitness enthusiasts"*\n\n[0:10-0:20]\n*AI generates 5 ad variations instantly*\n"Wait... these are actually good?!"\n\n[0:20-0:40]\n*Shows the generated ads*\n"Lace up and leave your limits behind..."\n"Every mile starts with a single step..."\n\n[0:40-0:60]\nThis is why 50K marketers use AI Marketing.\nLink in bio to try free.', visual_notes: 'Screen recording with face cam reaction. Trending audio. Text overlays. Fast cuts.', voiceover_text: 'Natural, Gen-Z friendly voice. Genuine surprise reactions.', status: 'published' },
      { title: 'How-To Tutorial: Email Campaigns', video_type: 'YouTube', duration_seconds: 480, script_content: '[INTRO - 0:00-0:30]\nHey everyone! In this tutorial, I\'ll show you exactly how to create a complete email campaign using AI Marketing in under 10 minutes.\n\n[STEP 1 - 0:30-2:00]\nFirst, let\'s set up our campaign. Click on "Email Campaigns" and then "New Campaign." Choose your campaign type - we\'ll do a promotional email today.\n\n[STEP 2 - 2:00-4:00]\nNow, let\'s tell the AI about our offer. I\'ll enter: "20% off summer sale, targeting previous customers, friendly and urgent tone." Watch as it generates the subject line, preview text, and full email body.\n\n[STEP 3 - 4:00-6:00]\nLet\'s customize. You can regenerate any section, adjust the tone, or edit directly. I\'ll tweak this CTA to be more specific.\n\n[STEP 4 - 6:00-7:00]\nNow let\'s generate some A/B test variations. Click "Generate Variations" and you\'ll get 3 alternative versions to test.\n\n[CONCLUSION - 7:00-8:00]\nAnd that\'s it! A complete email campaign with A/B variations in under 8 minutes. If you found this helpful, subscribe for more tutorials!', visual_notes: 'Screen recording with cursor highlights. Zoom on important features. Chapter markers. End screen with subscribe button.', voiceover_text: 'Clear, instructional tone. Friendly and patient.', status: 'published' },
      { title: 'Instagram Reels - Quick Tips', video_type: 'Instagram Reels', duration_seconds: 30, script_content: '[0:00-0:05]\n3 AI copywriting hacks in 30 seconds:\n\n[0:05-0:12]\n#1: Always include your target audience for better results\n\n[0:12-0:20]\n#2: Specify the tone - "friendly" vs "professional" makes a huge difference\n\n[0:20-0:27]\n#3: Generate multiple variations and A/B test them\n\n[0:27-0:30]\nFollow for more tips!', visual_notes: 'Quick cuts with text overlays. Number animations. Product screenshots. Trending music.', voiceover_text: 'Fast, energetic voice. Clear enunciation.', status: 'published' },
      { title: 'Explainer: How AI Copywriting Works', video_type: 'YouTube', duration_seconds: 300, script_content: '[INTRO - 0:00-0:30]\nEver wondered how AI can write marketing copy? In this video, we\'ll break down the technology behind AI copywriting in simple terms.\n\n[SECTION 1 - 0:30-1:30]\nAt its core, AI copywriting uses large language models - think of them as incredibly sophisticated pattern recognition systems trained on billions of words.\n\n[SECTION 2 - 1:30-2:30]\nWhen you give the AI a prompt like "write a Facebook ad for coffee," it predicts the most likely words that would follow based on patterns in successful marketing copy.\n\n[SECTION 3 - 2:30-4:00]\nBut here\'s where it gets interesting. Our AI isn\'t just trained on any text - it\'s fine-tuned on millions of high-converting marketing pieces. So it doesn\'t just write words; it writes words that sell.\n\n[CONCLUSION - 4:00-5:00]\nThe result? Copy that sounds human, follows proven frameworks, and converts. That\'s the power of AI copywriting.', visual_notes: 'Animated explainer graphics. Neural network visualizations. Before/after examples. Clean, modern aesthetic.', voiceover_text: 'Authoritative but accessible. Educational tone.', status: 'published' },
      { title: 'LinkedIn Video Ad', video_type: 'LinkedIn Ad', duration_seconds: 45, script_content: '[0:00-0:10]\nMarketing teams are spending 40% of their time on content creation. There\'s a better way.\n\n[0:10-0:25]\nAI Marketing helps enterprise teams generate on-brand content 10x faster. Ad copy, emails, social posts - all aligned with your brand voice.\n\n[0:25-0:40]\nJoin companies like Salesforce, Adobe, and HubSpot who trust AI Marketing for their content needs.\n\n[0:40-0:45]\nBook a demo today.', visual_notes: 'Professional, corporate aesthetic. Enterprise logos. Clean transitions. Business-appropriate visuals.', voiceover_text: 'Professional, confident voice. Business tone.', status: 'published' },
      { title: 'YouTube Pre-Roll Ad (15 sec)', video_type: 'YouTube Pre-Roll', duration_seconds: 15, script_content: '[0:00-0:05]\nWriting marketing copy takes forever.\n\n[0:05-0:12]\nUnless you use AI Marketing. Generate ads, emails, and more in seconds.\n\n[0:12-0:15]\nTry free at aimarketing.com', visual_notes: 'Fast cuts. Before/after comparison. Logo and URL prominent. Skippable after 5 seconds so hook is crucial.', voiceover_text: 'Punchy, direct delivery. Every word counts.', status: 'published' },
      { title: 'Webinar Promo Video', video_type: 'Promotional', duration_seconds: 90, script_content: '[INTRO - 0:00-0:15]\nWant to 10x your marketing output without 10x the effort? You won\'t want to miss this.\n\n[DETAILS - 0:15-0:45]\nJoin us for a free masterclass: "10X Your Marketing with AI" hosted by Sarah Johnson, our CMO.\n\nYou\'ll learn:\n- AI prompting secrets for better copy\n- Workflow automation strategies\n- Real case studies from top brands\n\n[LOGISTICS - 0:45-1:10]\nDate: February 15th, 2024\nTime: 2:00 PM Eastern\nDuration: 60 minutes + live Q&A\n\n[CTA - 1:10-1:30]\nSeats are limited to 500 attendees. Reserve your spot now at the link below. See you there!', visual_notes: 'Host intro shot. Bullet point animations. Calendar graphic. Registration countdown. Professional but approachable.', voiceover_text: 'Engaging, inviting tone. Build excitement.', status: 'published' },
      { title: 'App Store Preview Video', video_type: 'App Preview', duration_seconds: 30, script_content: '[0:00-0:08]\nAI Marketing - Create compelling copy on the go.\n\n[0:08-0:15]\n*Show app interface*\nGenerate ads, emails, and social posts anywhere.\n\n[0:15-0:22]\n*Show one-tap generation*\nPowerful AI at your fingertips.\n\n[0:22-0:30]\nDownload free on the App Store.', visual_notes: 'Device frame showing app. Smooth scrolling demo. Feature highlights. App Store badge at end.', voiceover_text: 'Clean, modern voice. Apple-style narration.', status: 'published' },
      { title: 'Brand Story Documentary', video_type: 'Brand Film', duration_seconds: 180, script_content: '[OPENING - 0:00-0:30]\n*Shots of marketers working late, stressed*\nEvery day, millions of marketers face the same challenge: creating content that connects.\n\n[PROBLEM - 0:30-1:00]\n*Interview clips*\n"I spent 60% of my time just writing copy..."\n"We couldn\'t afford professional copywriters..."\n"Quality was inconsistent across our team..."\n\n[SOLUTION - 1:00-1:30]\n*Founder speaking*\nWe started AI Marketing with a simple belief: great marketing copy shouldn\'t be a privilege. It should be accessible to everyone.\n\n[IMPACT - 1:30-2:30]\n*Customer success stories*\nToday, over 100,000 businesses use AI Marketing to create content that converts. From solo entrepreneurs to Fortune 500 companies.\n\n[VISION - 2:30-3:00]\nThis is just the beginning. We\'re building the future of marketing - one where creativity is amplified, not replaced, by AI.', visual_notes: 'Cinematic quality. Documentary style. Mix of interviews, b-roll, and product shots. Emotional music.', voiceover_text: 'Warm, inspiring narrator. Documentary tone.', status: 'draft' },
      { title: 'Comparison: AI vs Human Copywriter', video_type: 'YouTube', duration_seconds: 360, script_content: '[INTRO - 0:00-0:30]\nAI vs human copywriter - who wins? We put them to the test with a real marketing challenge.\n\n[SETUP - 0:30-1:30]\nThe challenge: Write 5 Facebook ad variations for a new fitness app.\nThe contestants: Our AI Marketing tool vs. Sarah, a professional copywriter with 10 years of experience.\nThe judge: You - and real A/B test data.\n\n[ROUND 1 - 1:30-3:00]\n*Split screen of AI and Sarah working*\nSarah takes 45 minutes to write her 5 ads.\nAI Marketing generates 5 ads in 47 seconds.\n\n[ROUND 2 - 3:00-4:30]\nNow let\'s compare quality. We ran both sets of ads with a $500 budget each.\n*Shows results*\nAI ads: 2.3% CTR, $1.82 CPA\nHuman ads: 2.1% CTR, $2.04 CPA\n\n[CONCLUSION - 4:30-6:00]\nThe results? Surprisingly close. AI was faster and slightly outperformed on metrics. But here\'s the real insight: the best results came from combining both - using AI for first drafts and human creativity for refinement.', visual_notes: 'Split screen comparison. Timer graphics. Data visualizations. Side-by-side ad displays. Professional production.', voiceover_text: 'Objective, journalistic tone. Let results speak.', status: 'published' },
      { title: 'Customer Onboarding Welcome', video_type: 'Onboarding', duration_seconds: 120, script_content: '[WELCOME - 0:00-0:20]\nWelcome to AI Marketing! I\'m so excited you\'re here. In the next 2 minutes, I\'ll show you how to create your first piece of content.\n\n[STEP 1 - 0:20-0:50]\nFirst, let\'s set up your brand profile. Click on Settings, then Brand Voice. Add your company name, industry, and describe your brand personality. This helps the AI match your unique voice.\n\n[STEP 2 - 0:50-1:20]\nNow let\'s create something! Go to the dashboard and pick a content type. Let\'s start with a social post. Enter your topic, select your platform, and click Generate.\n\n[STEP 3 - 1:20-1:40]\nBoom! Your first AI-generated content. You can regenerate, edit, or save it to your library.\n\n[NEXT STEPS - 1:40-2:00]\nExplore the other content types and check out our tutorials for advanced tips. If you need help, our support team is just a click away. Happy creating!', visual_notes: 'Friendly host on camera. Screen recordings. Highlight clicks and features. Celebratory animation on completion.', voiceover_text: 'Warm, welcoming, encouraging. Like a friend showing you around.', status: 'published' },
      { title: 'Annual Review Highlight Reel', video_type: 'Corporate', duration_seconds: 150, script_content: '[INTRO - 0:00-0:15]\n2023 was our biggest year yet. Here\'s what we accomplished together.\n\n[METRICS - 0:15-0:45]\n*Animated counters*\n100,000+ users\n10 million+ content pieces generated\n$50M Series B raised\n50+ new features launched\n\n[HIGHLIGHTS - 0:45-1:30]\n*Quick montage*\nLaunched video script generator\nExpanded to 25 languages\nOpened London office\nWon TechCrunch Disrupt\nNamed to Forbes AI 50\n\n[TEAM - 1:30-2:00]\n*Team photos and clips*\nGrew from 25 to 100 team members\nHired industry leaders from Google, Meta, and HubSpot\n\n[LOOKING AHEAD - 2:00-2:30]\nIn 2024, we\'re doubling down on innovation. New AI models, new features, new markets. The future of marketing is AI, and we\'re just getting started.\n\nThank you for being part of our journey.', visual_notes: 'High-energy montage. Achievement graphics. Team celebration shots. Forward-looking visuals. Inspiring music crescendo.', voiceover_text: 'Proud, celebratory tone. Building excitement for future.', status: 'draft' }
    ];

    for (const script of videoScripts) {
      await client.query(
        'INSERT INTO video_scripts (user_id, title, video_type, duration_seconds, script_content, visual_notes, voiceover_text, status) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)',
        [userId, script.title, script.video_type, script.duration_seconds, script.script_content, script.visual_notes, script.voiceover_text, script.status]
      );
    }
    console.log('Video scripts seeded: 15 items');

    console.log('\n✅ Database seeding completed successfully!');
    console.log('Demo credentials: demo@aimarketing.com / demo123');

  } catch (error) {
    console.error('Error seeding database:', error);
    throw error;
  } finally {
    client.release();
    await pool.end();
  }
}

seed().catch(console.error);
